puts "🌱 Seeding spices..."

Recipe.create(name: "Molten Lava Cake", instructions: "Start by preheating your oven to 400 degrees F. Next, go ahead and coat the 2 ramekins with non-stick spray. After that, you want to melt the chocolate and butter in the microwave until smooth. Now, add the powdered sugar and stir. Then, add both the egg and the egg yolk and mix completely. Add flour and cocoa powder and stir to combine. In ramekins, divide the batter and bake for 13 minutes, or until the edges are firm but the center is jiggly. Allow the cake to cool for 2 minutes, then invert it onto a serving plate. Finally, top your Gordon Ramsay Molten Lava Cake with some powdered sugar.", image_url: "https://ourtableforseven.com/wp-content/uploads/2021/12/3-4-1.jpg.webp", hours: 1, ingredients: "chocolate, butter, powdered sugar, eggs, flour, cocoa powder", rating: 5, chef_id: 1)
Recipe.create(name: "Lobster Pasta", instructions: "Start with filling up 3/4th of a casserole dish with water then add salt. Put the herbs and the pepper inside.
Boil the water and add the lobster. Place the casserole dish over medium heat and cook the lobster for 15-20 minutes. Set aside the lobster and drain the stock. Keep some of the stock for the sauce (about 1 1/2 glasses). Cut the lobster meat into small cubes.
In a new casserole, bring the stock back to a boil and add the spaghetti, cooking for 7 minutes. Drain the spaghetti and keep it hot while preparing the sauce. Add onion, thyme, basil, and sugar to a deep, wide pan. Stir the onion and herbs in the oil while heating until the onion becomes slightly brown in color. Pour in the vinegar after the onion is slightly browned. Let the vinegar evaporate and then add the tomato pulp to the pan. Sprinkle the oregano, garlic, and salt over the mixture. Stir well and cook for about 4 minutes. Add the lobster stock and simmer on low heat. If necessary, add a half glass of lukewarm water. Then, add the lobster meat. Cook the sauce for almost 20 minutes until it has thickened. The spaghetti should be placed in a big wide baking pan, drizzled with a little olive oil, about 2-3 tsp. Mix the spaghetti and then add the sauce. Mix the sauce gently with the spaghetti. Leave the food to rest for 5 minutes. Top with dill and serve.", image_url: "https://ourtableforseven.com/wp-content/uploads/2022/08/13-16-683x1024.jpg.webp", hours: 1, ingredients: "lobster, spaghetti, onion, thyme, basil, pepper seeds, sea salt, tomatoes, garlic, oregano, sugar, olive oil, salt, pepper, dill", rating: 4, chef_id: 1)
Recipe.create(name: "Turkey Breast", instructions: "Turn the oven up to 400 degrees Fahrenheit. After rinsing, blot the turkey breast dry with paper towels. First, carefully remove the skin from the meat of the turkey using your fingers, and then spread the butter that has been melted under the skin. Put the turkey breast in a roasting pan or on a baking sheet with a rim and put it in the oven. First, drizzle the wine over the breast, and then squeeze the juice of the lemon over it. After seasoning with kosher salt and pepper, scatter cloves of garlic and thyme leaves over the surface of the wine. Roast the turkey for 45-60 minutes for bone-in breasts or 30 minutes for boneless breasts, or until an instant-read thermometer put into the middle of the breast registers 150-155 degrees Fahrenheit, whichever comes first. As the turkey cooks, replenish the pan with additional wine as necessary to prevent the aromatics from being scorched. Before slicing, cover with foil and let it rest for at least ten minutes; the interior temperature should reach 160 degrees Fahrenheit during this time. Reserve pan drippings for gravy if preferred.", image_url: "https://ourtableforseven.com/wp-content/uploads/2022/08/13-56.jpg.webp", hours: 2, ingredients: "turkey breast, butter, lemon, garlic, thyme, salt, pepper", rating: 3, chef_id: 2)
Recipe.create(name: "Stuffed Poblano Peppers", instructions: "Preheat the oven to 350 degrees Fahrenheit. Spray a baking sheet with nonstick cooking spray. Arrange the poblano peppers in a single layer on the pan. Bake for 10-15 minutes, or until the peppers are softened. In a large skillet over medium-high heat, heat the oil. Cook for 5-6 minutes, breaking up the ground beef with a spatula until the meat is cooked through.
Cook for 30 seconds after adding the garlic. Add the taco seasoning packet and 2 tablespoons of water. Stir in the spice to coat the meat. To the pan, add the rice, beans, corn, tomatoes, and 3/4 of the cheese. Remove the pan from the heat and whisk everything together. Divide the beef mixture among the peppers equally. Finish with the remaining cheese. Place the peppers back in the oven. Bake for 10-15 minutes, or until the cheese is completely melted. Serve garnished with cilantro.", image_url: "https://ourtableforseven.com/wp-content/uploads/2021/11/5-8-2-683x1024.png.webp", hours: 2, ingredients: "poblano peppers, vegetable oil, ground beef, garlic, taco seasoning, white rice, black beans, corn kernels, petite diced tomatoes, shredded Monterey Jack cheese, cilantro, cooking spray", rating: 5, chef_id: 3)
Recipe.create(name: "Candied Yams", instructions: "Begin by preheating your oven to 450°F.Toss the sliced sweet potatoes with vegetable oil and spread them out equally on a baking pan. Place them in the oven and bake for about 30 minutes, or until tender, soft, and caramelized. Keep an eye on your yams while they bake, as you want to remove them from the oven as soon as they get black to avoid them from burning. Heat a saucepan over medium-high heat, then add the butter, brown sugar, corn syrup, and water and cover lightly with cooking spray. Continue stirring until the sugar is completely dissolved; when it begins to boil, decrease the heat and simmer for approximately 5 minutes. Remove the pan from the heat when you observe a thick and mildly bubbling mixture. Finally, when the yams are done, pour the sauce over them and coat evenly before serving.", image_url: "https://ourtableforseven.com/wp-content/uploads/2021/11/49-2.jpg.webp", hours: 1, ingredients: "yams, butter, brown sugar, miniature marshmallows", rating: 4, chef_id: 4)
Recipe.create(name: "Asparagus Casserole", instructions: "Place a rack in the top third of your oven and turn it on to broil. Next, lightly spray a 2-quart baking dish that can go under the broiler with non-stick spray. In a small bowl, mix the panko, Parmesan, and lemon zest together. Pour 2 tablespoons of melted butter on top and stir to moisten.
In the meantime, heat the oil and last tablespoon of butter over medium heat in a large, wide pan or Dutch oven. Add the asparagus, onion, and mushrooms and cook, stirring often, for about 15 minutes, or until the onions and mushrooms are soft, golden, and have given up their liquid. Now, add the flour and continue cooking, stirring, for another minute or two, until all the flour turns golden and there are no white bits left. 4Pour the milk in a few splashes at a time, stirring after each one to keep the mixture from getting lumpy. Then, turn up the heat to medium-high. Salt, pepper, basil, and nutmeg go in next.
Cook and stir the sauce until it starts to bubble. Use a wooden spoon or rubber spatula to scrape the bottom of the pan to keep it from sticking. As the sauce reduces and thickens, stir it often until, after about 8 to 10 minutes, it looks like creamy gravy. At the end, run your spoon or spatula frequently along the bottom to keep the sauce from sticking. Take the sauce off the stove. Stir in the Greek yogurt, 1 tablespoon of lemon juice, and fresh basil. Taste the seasonings and change them as you like. Pour the mixture into an even layer in a baking dish. Spread the mixture of breadcrumbs on top.
Put your casserole in the oven and broil it for 1 to 3 minutes, or until it starts to bubble and get brown. Let it sit for 5 to 10 minutes before serving, and then add more fresh basil as a garnish.", image_url: "https://ourtableforseven.com/wp-content/uploads/2022/08/6-45.jpg.webp", hours: 1, ingredients: "asparagus, mushrooms, milk, flour, dried basil, nutmeg, salt, pepper, greek yogurt, panko", rating: 5, chef_id: 4)
Recipe.create(name: "Slow-Roasted Cherry Tomatoes", instructions: "Preheat the oven to 250 degrees Fahrenheit. To make cleanup easier, line a large baking sheet with parchment paper. Place aside. Preparation of the tomatoes: Slice the tomatoes. The tomatoes must be consistent in size so that they roast properly, so depending on their size, you may want to split or quarter them. Place the tomatoes on the prepared baking sheet, and cut side up. Drizzle the olive oil over the tomatoes, then sprinkle with the garlic, thyme, salt, and crushed red pepper flake (if using). Slow roast the tomatoes: Preheat the oven to 350°F. Slow roast for 2 1/2 – 3 hours, or until desired dehydration. I like to set a timer every 60 minutes to check on them while they roast. Serve! Enjoy your slow-roasted tomatoes right away (try not to eat them all straight from the pan — it’ll be tempting!). They’re delicious on their own, piled into your favorite summer sandwich, thrown in a fast summer spaghetti, or presented as an antipasti cheese board. Enjoy!", image_url: "https://ourtableforseven.com/wp-content/uploads/2022/04/5-57-683x1024.jpg.webp", hours: 3, ingredients: "cherry tomatoes, olive oil, garlic, crushed red chile, thyme", rating: 5, chef_id: 5)

Chef.create(first_name: "Gordon", last_name: "Ramsay", age: 56)
Chef.create(first_name: "Ina", last_name: "Garten", age: 75)
Chef.create(first_name: "Bobby", last_name: "Flay", age: 58)
Chef.create(first_name: "Paula", last_name: "Deen", age: 76)
Chef.create(first_name: "Jamie", last_name: "Oliver", age: 47)

puts "✅ Done seeding!"
